name: Build Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: devops-challenge-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build imagem Docker
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./app

      - name: Testar imagem localmente (opcional)
        run: |
          docker run -d -p 8080:8080 $IMAGE_NAME:$IMAGE_TAG
          sleep 5
          curl -f http://localhost:8080/health
